language: python

sudo: required

branches:
  only:
    - master


before_install:
  - source devtools/travis-ci/install.sh 
  - export PYTHONUNBUFFERED=true


install:


script: 
  - source activate myenv 
  - nosetests -v  

env:
  matrix:
    - python=2.7  CONDA_PY=27
    #- python=3.4  CONDA_PY=34

global:
  - ORGNAME="omnia"



after_success:
  - echo "after_success"

