language: python
python:
  - "3.6"

branches:
  only:
    - networkx2
    - master 

before_install:
  - source devtools/travis-ci/install.sh 
  - export PYTHONUNBUFFERED=true
# command to install dependencies
install:
  - pip install nose
  - python setup.py install
# command to run tests
script:
  - nosetests -v

  after_success:
  - echo "...DONE..."

notifications:
  email: antonia.mey@ed.ac.uk
