language: python

sudo: false

branches:
  only:
    - master


before_install:
  - source devtools/ci/install.sh 
  - export PYTHONUNBUFFERED=true


install:


script:  
  - conda config --add channels ${ORGNAME}
  - conda build devtools/conda-recipe
  - conda install --yes --quiet pip nose nose-timer
  - source activate _test
  - nosetests -v  

env:
  matrix:
    - python=2.7  CONDA_PY=27
    #- python=3.4  CONDA_PY=34

global:
  - ORGNAME="omnia":
  - PACKAGENAME="lomap"


after_success:
  - echo "after_success"

