language: python

sudo: false

branches:
  only:
    - networkx2
    - master 


before_install:
  - source devtools/travis-ci/install.sh 
  - export PYTHONUNBUFFERED=true


install: true


script: 
  - python setup.py install
  - conda install --yes pip nose
  - pip install nose-timer
  - nosetests -v

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36

  global:
    - ORGNAME="nividic"
    - PACKAGENAME="lomap"


after_success:
  - echo "...DONE..."

notifications:
  email: false