language: python

sudo: false

branches:
  only:
    - master


before_install:
  - source devtools/travis-ci/install.sh 
  - export PYTHONUNBUFFERED=true


install: true


script: 
  - conda config --add channels ${ORGNAME}
  - conda build devtools/conda-recipe 
  - source activate _test
  - conda install --yes --quiet pip nose nose-timer
  - echo "HERE>>>>>>>>>>>>>>>>>>"
  - pwd
  - ls

env:
  matrix:
    - python=2.7  CONDA_PY=27
    #- python=3.4  CONDA_PY=34

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="lomap"


after_success:
  - echo "after_success"


notifications:
  email: false