language: python

sudo: false

branches:
  only:
    - master


before_install:
  - source devtools/travis-ci/install.sh 
  - export PYTHONUNBUFFERED=true


install: true


script: 
  - conda config --add channels ${ORGNAME}
  - conda build --no-build-id devtools/conda-recipe 
  - conda create -n _test --yes
  - source activate _test
  - conda install --use-local lomap --yes
  - conda install --yes pip nose
  - pip install nose-timer
  - nosetests -v

env:
  matrix:
    - CONDA_PY=27


  global:
    - ORGNAME="nividic"
    - PACKAGENAME="lomap"


after_success:
  - echo "...DONE..."

notifications:
  email: false