language: python
matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - PYTHON_VER=3.6
    - os: linux
      python: 3.5
      env:
        - PYTHON_VER=3.5

branches:
  only:
    - devel
    - master 

before_install: 
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - conda install -c rdkit rdkit=2016
  - conda install networkx
  - conda install matplotlib=1.5
  - conda install pip nose
  - conda install pyqt=4
  - conda install pygraphviz
  - pip install nose-timer
  - pip install codecov
install: yes

script:
  - python setup.py install
  - nosetests -v --with-coverage

after_success:
  - echo "...DONE..."
  - codecov
notifications:
  email: false
