package:
  name: lomap
  version: "0.0.0"

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  skip:
    - [not unix]

requirements:
  build:
    - python
    - boost
    - setuptools
    - rdkit
    - matplotlib
    - pyqt ==4.11.4
    - networkx ==2.1
    - graphviz
    - pygraphviz
    - pillow
    - nose

  run:
    - python
    - boost
    - rdkit 
    - matplotlib
    - pyqt
    - networkx ==2.1
    - graphviz
    - pygraphviz
    - pillow

test:
  requires:
    - nose
  imports:
    - lomap
  commands:
   - which lomap
   - lomap -h
   - nosetests -v
   
about:
  home: https://github.com/MobleyLab/Lomap
  license: LGPL
  license_file: LICENCE.txt
  summary: Alchemical free-energy calculations planner
